name: Test

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code
  pull-requests: read # for golangci/golangci-lint-action to fetch pull requests

env:
  # https://github.com/actions/setup-go/issues/491
  GOTOOLCHAIN: local

jobs:
  test:
    strategy:
      # Default is true, cancels jobs for other platforms in the matrix if one fails
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        go:
          - '1.25'

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: read
      actions: write # to allow uploading artifacts and cache
    steps:

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: Get dependencies
      run: |
        go get -v

    - name: Run linter
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: latest
        args: --timeout 5m

    - name: Download MaxMindDB binary
      run: |
        wget https://github.com/P3TERX/GeoLite.mmdb/releases/latest/download/GeoLite2-Country.mmdb

    # Commented bits below were useful to allow the job to continue
    # even if the tests fail, so we can publish the report separately
    # For info about set-output, see https://stackoverflow.com/questions/57850553/github-actions-check-steps-status
    - name: Run tests
      run: |
        go test -v -failfast ./... -tags=it

    - name: Run rule-translator unit tests
      run: |
        python3 -m unittest -v test_get_owasp_rules
